version: '2.4'

services:
  kodi-mariadb:
    image: linuxserver/mariadb
    container_name: kodi-mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=kodi
      - TZ=Pacific/Auckland
    volumes:
      - ./mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped

  kodi-headless:
    image: matthuisman/kodi-headless:Nexus
    container_name: kodi-headless
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_HOST=kodi-mariadb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=kodi
      - TZ=Pacific/Auckland
    volumes:
      - ./kodi/:/config/.kodi
    ports:
      - 8080:8080
      - 9090:9090
      - 9777:9777/udp
    depends_on:
      - kodi-mariadb
    restart: unless-stopped
