name: matthuisman/kodi-headless
run-name: ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  build_amd64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: hub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build
      uses: docker/build-push-action@v2
      with:
        context: .
        pull: true
        push: true
        platforms: linux/amd64
        tags: matthuisman/kodi-headless:${{ github.ref_name }}-amd64

  build_arm64:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: hub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup buildx
      uses: docker/setup-buildx-action@v2

    - name: build
      uses: docker/build-push-action@v2
      with:
        context: .
        pull: true
        push: true
        platforms: linux/arm64/v8
        tags: matthuisman/kodi-headless:${{ github.ref_name }}-arm64

  build_arm:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: hub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup buildx
      uses: docker/setup-buildx-action@v2

    - name: build
      uses: docker/build-push-action@v2
      with:
       # file: ./Dockerfile.arm
        context: .
        pull: true
        push: true
        platforms: linux/arm/v7
        tags: matthuisman/kodi-headless:${{ github.ref_name }}-arm
        build-args: |
          CMAKE_ARGS=-DWITH_CPU=arm|-DCMAKE_C_FLAGS="-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad"|-DCMAKE_CXX_FLAGS="-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad"

  combine:
    needs: [build_amd64, build_arm64, build_arm]
    runs-on: ubuntu-latest

    steps:
    - name: hub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create and push manifest images
      uses: Noelware/docker-manifest-action@master
      with:
        base-image: matthuisman/kodi-headless:${{ github.ref_name }}
        extra-images: matthuisman/kodi-headless:${{ github.ref_name }}-amd64,matthuisman/kodi-headless:${{ github.ref_name }}-arm64,matthuisman/kodi-headless:${{ github.ref_name }}-arm
        push: true
